name: Test Secret

on:
    push:
        branches:
            - main

jobs:
    test-secret:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up environment
              env:
                  API_KEY: ${{ secrets.API_KEY }}
              run: |
                  echo "API Key: $API_KEY"
